apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-microservice
  labels:
    name: hello-microservice
    app: hello-microservice
data:
  application.yaml: |-
    spring:
      application:
        name: hello-microservice
      cloud:
        loadbalancer:
          enabled: false
    springdoc:
      swagger-ui:
        path: /swagger-docs
      api-docs:
        path: /api-docs
    app:
      version: 1.0.0
    management:
      endpoints:
        web:
          exposure:
            include:
              - health
              - info