apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_BROKER_ID
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_LISTENERS
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: KAFKA_ZOOKEEPER_CONNECT
        - name: ALLOW_PLAINTEXT_LISTENER
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: ALLOW_PLAINTEXT_LISTENER