spring:
  application:
    name: activity
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: activity
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
springdoc:
  swagger-ui:
    path: /swagger-docs
    disable-swagger-default-url: true
  api-docs:
    path: /docs
app:
  mvc:
    context-path: /v1
  client:
    employee:
      url: ${EMPLOYEE_SERVICE_HOST}
      path:
        base-path: /api/v1
        find-employee: /employees
        find-group: /groups/{groupId}
server:
  servlet:
    context-path: /api