spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
security:
  token:
    secret: secret
    expire: 10000000
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-docs
  api-docs:
    path: /docs