apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  ## Encoding in BASE64, there's "mongodb" both in MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29kYg==
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29kYg==