spring:
  application:
    name: hello-microservice
springdoc:
  swagger-ui:
    path: /swagger-docs
  api-docs:
    path: /api-docs
app:
  version: @project.version@
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info