apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gateway
  labels:
    name: hello-gateway
    app: hello-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gateway
  template:
    metadata:
      name: hello-gateway
      labels:
        app: hello-gateway
    spec:
      serviceAccountName: hello-gateway
      containers:
        - name: hello-gateway
          image: chainichek/hello-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          args:
            - "--spring.cloud.bootstrap.enabled=true"
            - "--spring.cloud.kubernetes.config.name=hello-gateway"
      restartPolicy: Always