apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-gateway
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - "pods"
      - "services"
      - "endpoints"
      - "configmaps"
    verbs:
      - "get"
      - "list"
      - "watch"