apiVersion: v1
kind: Service
metadata:
  name: hello-gateway
  labels:
    name: hello-gateway
    app: hello-gateway
spec:
  selector:
    app: hello-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
  